# CI build definition for https://ci.appveyor.com/project/olegsych/t4toolbox
# To learn more, see http://www.appveyor.com/docs/appveyor-yml 

version: 15.0.0.{build}

image: Visual Studio 2022

branches:
  only:
  - master

pull_requests: 
  do_not_increment_build_number: true 

skip_tags: true

configuration: Release

environment:
  T4ToolboxSnk:
    secure: qikNDVTVELcu7WnxruC2+vO9vOdK0whuxosiF5xiV2vI1v/UNno8rtqhoYgKjGoI4IxTvUEtOseNKqF6n0LjKjC2KiiqQj+zvdbkghr9GmWGFiCw27QlbbO/NU9+xWLULt8WxuOTHp681290l304YGRyE2SS2Tb0i86XJXJ5BXC5YvMgK6woVCOHCEITiTmUZBwppFoc5IR3bnyXSSLimLXP0mYPuT+zzPGit2V6HA5VmrXUe8K4DJ1NYDATmcztKusz1klcVzIrtQiII4CWKBvmHHk8g6Hoy8sWHb4CtzHr8QeCvcBwpb6TINLY71M620ELKBczMf2HAUvmcyNY9v+eFnJ8Vcz0gc5o0ENLQ8A/f0i6v57MqnBC9g9WH3kLCNGKe2GVhSdx9+cnaoD5Lnwt3+Qyi9N8UxbGg9yRzSG7u+PU2d/OvneT/r0AGqFIau/yBjSFL3QVMX6j3ycfH653UQOoM/Y8cbyf89tCtz810Y2/IQ4wXUTNEeXvlAiRDlRXPavfjvk8GlCf3ub0LoNbKAx2MXzLN1cQsPmdvCxT7Zlca2PKFwXp4PvIXT50f+QK1HPAn33X2WijYLc9IdiauyKHbP3hdf82b6jmdeCleaFpxRbOUbQyifldxURkla/dZNM5MjdQSMuwqohcK02+t+TzINKTNOQEyOM5JmllU8Y+csgX255G1DyxMNPlsGKor3yhAFsLalbcZu5VMCgPzxvDJSOs3ksAJF9IJB2GynM/Yzy76j8sGbRsx7GW8mT+TxIIiOd/+Y2n/C2jEKoA6RWorNjp1Bw2pjQvI5Z7p8bemTqOjNssQXFJ2m9xfamtlWqQAaBB2KAVjzSPyOCaKGqGXoUsY4XEkoDQ8Nlm0ZJfVGgzz4ccpX4Plhh6sIHThZU0nENypdqy/nNStOkKRw5MKnh57ObgL77bnrWHu0aWZhBfgVFQTo87WWxLEhWFnVfC8rXhXItdz+VWf4oCJ/nrxT13SeMYQ+/FETzF2TCMzP7tQvLRHLuNWNaPvJIsQ56g9uamZQDR7i1jvCjZ16RllA4Vv0y6z34ruaA=

before_build:
- nuget restore
- ps: >-
    Import-Module .\build\Module.psm1

    if (!$env:APPVEYOR_PULL_REQUEST_NUMBER) {
        CreateAssemblyKeyFile "T4ToolboxSnk" "T4Toolbox.snk"
    }

build:
  parallel: true
  verbosity: minimal

test:
  assemblies: '**\*.tests.dll'

artifacts:
- path: '**\T4Toolbox.*.vsix'